export const routerConstants = {
    REGISTRATION: 'registration',
    ABOUT_US: 'about-us',
    RESET_PASSWORD: 'reset-password',
    LOGIN: 'login',
    VERIFY_NUMBER: 'verify-number',
    PHONE_VERIFY: 'phone-verify',
    TERMS_OF_USE: 'terms-of-use',
    APPROVAL: 'approval',
    SELECT_LOGISTIC_POINT: 'select-logistic-point',
    DOCUMENT_VERIFICATION: 'document-verification',
    WAITING_VERIFICATION: 'waiting-verification',
    EDUCATIONAL_TEST: 'educational-test',
    EDUCATIONAL_TEXT: 'educational-text',
    EXAM: 'exam',
};
